config/routes.rb
SimpleForm::Application.routes.draw do
  resources :detalls do
    collection do
      match "/search/(:val)", :action => 'search'
    end
  end

  resources :users

  root :to => "users#index"
end

app/models/detall.rb
class Detall
  include Mongoid::Document
  field :age, type: String
  field :ihone, type: String

  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :pwd, type: String


   has_many :detall
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/detalls_controller.rb
class DetallsController < ApplicationController
  # GET /detalls
  # GET /detalls.json
  def index
    @detalls = Detall.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @detalls }
    end
  end

  # GET /detalls/1
  # GET /detalls/1.json
  def show
    @detall = Detall.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @detall }
    end
  end

  # GET /detalls/new
  # GET /detalls/new.json
  def new
    @detall = Detall.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @detall }
    end
  end

  # GET /detalls/1/edit
  def edit
    @detall = Detall.find(params[:id])
  end

  # POST /detalls
  # POST /detalls.json
  def create
    @detall = Detall.new(params[:detall])

    respond_to do |format|
      if @detall.save
        format.html { redirect_to @detall, notice: 'Detall was successfully created.' }
        format.json { render json: @detall, status: :created, location: @detall }
      else
        format.html { render action: "new" }
        format.json { render json: @detall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /detalls/1
  # PUT /detalls/1.json
  def update
    @detall = Detall.find(params[:id])

    respond_to do |format|
      if @detall.update_attributes(params[:detall])
        format.html { redirect_to @detall, notice: 'Detall was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @detall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalls/1
  # DELETE /detalls/1.json
  def destroy
    @detall = Detall.find(params[:id])
    @detall.destroy

    respond_to do |format|
      format.html { redirect_to detalls_url }
      format.json { head :no_content }
    end
  end

  def search
    @deta = Detall.where(:age => params[:val])
    respond_to do |format|
      format.html { render :json => @deta }
      format.json { render :json => @deta }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/detalls_helper.rb
module DetallsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/detalls/_form.html.erb
<%= form_for(@detall) do |f| %>
  <% if @detall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detall.errors.count, "error") %> prohibited this detall from being saved:</h2>

      <ul>
      <% @detall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :ihone %><br />
    <%= f.text_field :ihone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/detalls/edit.html.erb
<h1>Editing detall</h1>

<%= render 'form' %>

<%= link_to 'Show', @detall %> |
<%= link_to 'Back', detalls_path %>

app/views/detalls/index.html.erb
<h1>Listing detalls</h1>

<table>
  <tr>
    <th>Age</th>
    <th>Ihone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @detalls.each do |detall| %>
  <tr>
    <td><%= detall.age %></td>
    <td><%= detall.ihone %></td>
    <td><%= link_to 'Show', detall %></td>
    <td><%= link_to 'Edit', edit_detall_path(detall) %></td>
    <td><%= link_to 'Destroy', detall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Detall', new_detall_path %>

app/views/detalls/new.html.erb
<h1>New detall</h1>

<%= render 'form' %>

<%= link_to 'Back', detalls_path %>

app/views/detalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Age:</b>
  <%= @detall.age %>
</p>

<p>
  <b>Ihone:</b>
  <%= @detall.ihone %>
</p>


<%= link_to 'Edit', edit_detall_path(@detall) %> |
<%= link_to 'Back', detalls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleForm</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
<%= f.input :pwd, :as =>:chosen, :input_html => { :chosen_class => "wocaonema" , :style => "width:350px;", :url => "/detalls/search"} %>
<% end %>

 







<!--
<%= simple_form_for @user do |f| %>
  <%= f.input :name %> 
  <%= f.input :pwd %>  
  <%= f.association :detall, :collection => {"" => "没有匹配结果"}, :input_html => { :class => 'chzn-select wocaonema',:style => "width:350px;", :url => "/detalls/search"} %>
  <%= f.button :submit %>
<% end %>

 -->













































<!-- <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pwd %><br />
    <%= f.text_field :pwd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 
-->




<!-- <select data-placeholder="Choose a country..." style="width:350px;"  class="chzn-select wori"  tabindex="2"><option value=""></option>  </select>
<button class='btn btn-mini handle_click' rel='tooltip' data-original-title='处理'>我操</button>
<select data-placeholder="Choose a Country..." class="chzn-select worinima" style="width:350px;" tabindex="2">
          <option value=""></option> 
          <option value="United States">United States</option> 
          <option value="United Kingdom">United Kingdom</option> 
          <option value="Afghanistan">Afghanistan</option>  
          <option value="Gabon">Gabon</option> 
          <option value="Gambia">Gambia</option>    
          <option value="Vanuatu">Vanuatu</option> 
          <option value="Venezuela, Bolivarian Republic of">Venezuela, Bolivarian Republic of</option> 
          <option value="Viet Nam">Viet Nam</option> 
          <option value="Virgin Islands, British">Virgin Islands, British</option> 
          <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option> 
          <option value="Wallis and Futuna">Wallis and Futuna</option> 
          <option value="Western Sahara">Western Sahara</option> 
          <option value="Yemen">Yemen</option> 
          <option value="Zambia">Zambia</option> 
          <option value="Zimbabwe">Zimbabwe</option>
        </select>
<br/><br/><br/><br/>

<script type="text/javascript">
  $("select").chosen({
    tool:{
      add: {
        html: "<a href='#'><i class='icon-ok'></i></a>",
        click:  function() {

        }
      }
    },
    blur: function(){

    }
  });


</script>

app/views/users/_simple.html.erb
<%= simple_form_for @order do |f| %>
  <%= f.input :name %> 
  <%= f.input :pwd %> 
  <%= f.button :submit %>
<% end %>
 

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pwd</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.pwd %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Pwd:</b>
  <%= @user.pwd %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>